proxy:
  title: Shiny Proxy
  landing-page: /
  port: 8080
  authentication: none
  hide-navbar: true
  docker:
    internal-networking: true
  specs:
  - id: Starter_Application
    container-cmd: ["R", "-e", "options(shiny.autoreload = TRUE); shiny::runApp('./app' ,host='0.0.0.0', port=3838)"]
    container-image: shiny_app_docker
    container-network: sp-example-net
logging:
  file:
    /log/shinyproxy.log
